

export const dataDoctors = [
    {
        id: 0,
        lastName: "Zinser",
        firstName: "Betina",
        docImage: 'betina-zinser',
        tuition: "-",
        area: ["Clínica Médica"],
        publicServiceMode: "Turno Programado",
        schedules: "Hora Indicada",
        days: "Todos los Días",
        description: "El Dr. Betiana Zinser se especializa en Clínica Médica y atiende a pacientes con diversas condiciones médicas generales, ofreciendo consultas con turno programado y hora indicada todos los días en la clínica."
    },
    {
        id: 1,
        lastName: "Galeano",
        firstName: "Raul",
        docImage: 'raul-galeano',
        tuition: "-",
        area: ["Ecografías"],
        publicServiceMode: "Turno Programado",
        schedules: "Hora Indicada",
        days: "Todos los Días",
        description: "El Dr. Raul Galeano es especialista en Ecografías y realiza diagnósticos mediante esta técnica, brindando consultas con turno programado y hora indicada todos los días en la clínica."
    },
    {
        id: 2,
        lastName: "Rodriguez",
        firstName: "Elio",
        docImage: 'elio-rodriguez',
        tuition: "-",
        area: ["Ecografías", "Cirugía"],
        publicServiceMode: "Turno Programado",
        schedules: "Hora Indicada",
        days: "Todos los Días",
        description: "El Dr. Elio Rodriguez también se especializa en Ecografías, realizando diagnósticos mediante esta técnica y ofreciendo consultas con turno programado y hora indicada todos los días en la clínica."
    },
    {
        id: 3,
        lastName: "Liva",
        firstName: "Gustavo",
        docImage: 'gustavo-liva',
        tuition: "-",
        area: ["Ecografías", "Ginecología"],
        publicServiceMode: "Turno Programado",
        schedules: "Hora Indicada",
        days: "Todos los Días",
        description: "El Dr. Gustavo Liva, especialista en Ecografías, ofrece consultas con turno programado y hora indicada todos los días en la clínica, utilizando esta técnica para diagnósticos."
    },
    {
        id: 4,
        lastName: "Rodriguez",
        firstName: "Cristian",
        // docImage: 'cristian-rodriguez',
        tuition: "-",
        area: ["Ecografías", "Cirugía"],
        publicServiceMode: "Turno Programado",
        schedules: "Hora Indicada",
        days: "Todos los Días",
        description: "El Dr. Cristian Rodriguez, al igual que su colega Elio Rodriguez, es especialista en Ecografías, brindando consultas con turno programado y hora indicada todos los días en la clínica."
    },
    {
        id: 5,
        lastName: "Castillo",
        firstName: "Elias Hernan",
        docImage: 'elias-castillo',
        tuition: "-",
        area: ["Jefe de Internación Sala Común"],
        publicServiceMode: "",
        schedules: "",
        days: "Todos los Días",
        description: "El Dr. Elias Hernan Castillo ocupa el cargo de Jefe de Internación en Sala Común en la clínica, supervisando la internación de pacientes en esa área, aunque no se especifican sus horarios de atención."
    },
    {
        id: 6,
        lastName: "Ramos",
        firstName: "Mabel Florencia",
        // docImage: 'mabel-florencia-ramos',
        tuition: "-",
        area: ["Jefa de Sala en Terapia Intensiva", "Unidad Coronaria"],
        publicServiceMode: "",
        schedules: "",
        days: "Todos los Días",
        description: "La Dra. Mabel Florencia Ramos es la Jefa de Sala en Terapia Intensiva y Unidad Coronaria en la clínica, supervisando estas áreas, aunque no se especifican sus horarios de atención."
    },
    {
        id: 7,
        lastName: "Meana",
        firstName: "Julio",
        docImage: 'julio-meana',
        tuition: "-",
        area: ["Pediatría"],
        publicServiceMode: "Orden de Llegada",
        schedules: "8 - 12 y 16 - 20",
        days: "Todos los Días",
        description: "El Dr. Julio Meana, especialista en Pediatría, atiende a niños y adolescentes con orden de llegada de 8 a 12 y de 16 a 20, todos los días en la clínica."
    },
    {
        id: 8,
        lastName: "Ibarra",
        firstName: "Sandra",
        docImage: 'sandra-ibarra',
        tuition: "-",
        area: ["Ginecología"],
        publicServiceMode: "Turno Programado",
        schedules: "Hora Indicada",
        days: "Todos los Días",
        description: "La Dra. Sandra Ibarra, especialista en Ginecología, ofrece consultas con turno programado y hora indicada todos los días en la clínica, brindando atención en salud reproductiva femenina."
    },
    {
        id: 9,
        lastName: "Wendler",
        firstName: "Gisela",
        // docImage: 'gisela-wendler',
        tuition: "-",
        area: ["Ginecología"],
        publicServiceMode: "Turno Programado",
        schedules: "Hora Indicada",
        days: "Todos los Días",
        description: "La Dra. Gisela Wendler, al igual que la Dra. Sandra Ibarra, es especialista en Ginecología, brindando consultas con turno programado y hora indicada todos los días en la clínica."
    },
    {
        id: 11,
        lastName: "Kapluk",
        firstName: "Christian",
        docImage: 'cristian-kapluk',
        tuition: "-",
        area: ["Ginecología"],
        publicServiceMode: "Turno Programado",
        schedules: "Hora Indicada",
        days: "Todos los Días",
        description: "El Dr. Christian Kapluk, especialista en Ginecología, brinda consultas con turno programado y hora indicada todos los días en la clínica, enfocándose en la salud reproductiva femenina."
    },
    {
        id: 12,
        lastName: "Berecochea",
        firstName: "Olga",
        // docImage: 'olga-berecochea',
        tuition: "-",
        area: ["Ginecología", "Mastología"],
        publicServiceMode: "Turno Programado",
        schedules: "Hora Indicada",
        days: "1 Vez Por Mes",
        description: "La Dra. Olga Berecochea, especialista en Ginecología y Mastología, ofrece consultas con turno programado y hora indicada una vez al mes en la clínica, especializándose en salud mamaria y reproductiva femenina."
    },
    {
        id: 13,
        lastName: "Prividori",
        firstName: "Gianela",
        // docImage: 'gianela-prividori',
        tuition: "-",
        area: ["Ginecología", "Mastología"],
        publicServiceMode: "Turno Programado",
        schedules: "Hora Indicada",
        days: "1 Vez Por Mes",
        description: "La Dra. Gianela Prividori, al igual que la Dra. Olga Berecochea, es especialista en Ginecología y Mastología, brindando consultas con turno programado y hora indicada una vez al mes en la clínica."
    },
    {
        id: 14,
        lastName: "Martinez",
        firstName: "Cesar",
        docImage: 'cesar-martinez',
        tuition: "-",
        area: ["Gastroenterología"],
        publicServiceMode: "Orden de Llegada",
        schedules: "8 - 12 y 16 - 20",
        days: "Todos los Días",
        description: "El Dr. Cesar Martinez, especialista en Gastroenterología, atiende a pacientes con trastornos del sistema digestivo, con orden de llegada de 8 a 12 y de 16 a 20, todos los días en la clínica."
    },
    {
        id: 15,
        lastName: "Aguirre",
        firstName: "Ernesto",
        // docImage: 'ernesto-aguirre',
        tuition: "-",
        area: ["Cardiología", "Cardio Infantil"],
        publicServiceMode: "Turno Programado",
        schedules: "Hora Indicada",
        days: "1 Vez Por Mes",
        description: "El Dr. Ernesto Aguirre, especialista en Cardiología Infantil, brinda consultas con turno programado y hora indicada una vez al mes en la clínica, centrándose en enfermedades cardíacas en niños."
    },
    {
        id: 16,
        lastName: "Valdez",
        firstName: "Julio",
        // docImage: 'julio-valdez',
        tuition: "-",
        area: ["Cardiología", "Cardio Adultos"],
        publicServiceMode: "Turno Programado",
        schedules: "Hora Indicada",
        days: "1 vez por mes",
        description: "El Dr. Julio Valdez, especialista en Cardiología de Adultos, ofrece consultas con turno programado y hora indicada una vez al mes en la clínica, especializándose en enfermedades cardíacas en adultos."
    },
    {
        id: 17,
        lastName: "Torgoff",
        firstName: "Federico",
        docImage: 'federico-torgoff',
        tuition: "-",
        area: ["Cirugía"],
        publicServiceMode: "Orden de Llegada",
        schedules: "8 - 12 y 16 - 20",
        days: "Todos los Días",
        description: <span>El Dr. Federico Torgoff, especialista en Cirugía y <strong>Director de la Clínica Giuliani</strong>, brinda consultas con orden de llegada de 8 a 12 y de 16 a 20, todos los días. Además de realizar consultas, el Dr. Torgoff lleva a cabo diversas intervenciones quirúrgicas, supervisa la coordinación del equipo médico y se encarga de la gestión general de la clínica, asegurando que todos los servicios se ofrezcan con la más alta calidad y profesionalismo.</span>
    },
    {
        id: 20,
        lastName: "Obregon",
        firstName: "Luis",
        // docImage: 'luis-obregon',
        tuition: "-",
        area: ["Otorrinolaringología"],
        publicServiceMode: "Turno Programado",
        schedules: "Hora Indicada",
        days: "1 Vez Por Mes",
        description: "El Dr. Luis Obregon, especialista en Otorrinolaringología, ofrece consultas con turno programado y hora indicada una vez al mes en la clínica, centradas en trastornos del oído, nariz y garganta."
    },
    {
        id: 21,
        lastName: "Paz",
        firstName: "Rolando",
        docImage: 'rolando-paz',
        tuition: "-",
        area: ["Traumatología"],
        publicServiceMode: "Orden de Llegada",
        schedules: "8 - 12 y 16 - 20",
        days: "Todos los Días",
        description: "El Dr. Rolando Paz, especialista en Traumatología, atiende a pacientes con lesiones y trastornos del sistema musculoesquelético, con orden de llegada de 8 a 12 y de 16 a 20, todos los días en la clínica."
    },
    {
        id: 22,
        lastName: "Sanchez",
        firstName: "Gonzalo",
        // docImage: 'gonzalo-sanchez',
        tuition: "-",
        area: ["Traumatología"],
        publicServiceMode: "Turno Programado",
        schedules: "Hora Indicada",
        days: "Todos los Días",
        description: "El Dr. Gonzalo Sanchez, también especialista en Traumatología, brinda consultas con turno programado y hora indicada todos los días en la clínica, centrándose en lesiones y trastornos del sistema musculoesquelético."
    },
    {
        id: 23,
        lastName: "Longoni",
        firstName: "Natalia",
        // docImage: 'natalia-longoni',
        tuition: "-",
        area: ["Alergista"],
        publicServiceMode: "Turno Programado",
        schedules: "Hora Indicada",
        days: "1 Vez Por Mes",
        description: "La Dra. Natalia Longoni, especialista en Alergología, ofrece consultas con turno programado y hora indicada una vez al mes en la clínica, centradas en trastornos alérgicos."
    },
    {
        id: 24,
        lastName: "Tomei",
        firstName: "Mauricio",
        docImage: 'mauricio-tomei',
        tuition: "-",
        area: ["Neurología", "Electroencefalograma", "Electromiograma"],
        publicServiceMode: "Turno Programado",
        schedules: "Hora Indicada",
        days: "Todos los Días",
        description: "El Dr. Mauricio Tomei, especialista en Neurología, brinda consultas con turno programado y hora indicada todos los días en la clínica, centradas en trastornos neurológicos y pruebas diagnósticas asociadas."
    },
    {
        id: 25,
        lastName: "Maluk",
        firstName: "Daniel",
        // docImage: 'daniel-maluk',
        tuition: "-",
        area: ["Bioquímico", "Laboratorio"],
        publicServiceMode: "Orden de Llegada",
        schedules: "7hs - 13hs",
        days: "Todos los Días",
        description: "El Dr. Daniel Maluk, especialista en Bioquímica de Laboratorio, realiza análisis de muestras de laboratorio con orden de llegada de 7hs a 13hs, todos los días en la clínica."
    },
    {
        id: 26,
        lastName: "Alvarez",
        firstName: "Lourdes",
        // docImage: 'lourdes-alvarez',
        tuition: "-",
        area: ["Bioquímica", "Laboratorio"],
        publicServiceMode: "Orden de Llegada",
        schedules: "7hs - 13hs",
        days: "Todos los Días",
        description: "La Dra. Lourdes Alvarez, especialista en Bioquímica de Laboratorio, realiza análisis de muestras de laboratorio con orden de llegada de 7hs a 13hs, todos los días en la clínica."
    },
    {
        id: 27,
        lastName: "Bolgietti",
        firstName: "Jorge",
        // docImage: 'jorge-boglietti',
        tuition: "-",
        area: ["Guardias Rotativas"],
        publicServiceMode: "Orden de Llegada",
        schedules: "",
        days: "",
        description: "El Dr. Jorge Bolgietti se especializa en Guardias Rotativas y atiende a pacientes con diversos casos médicos, ofreciendo atención mediante orden de llegada en la clínica."
    }
]